### ISSUE TITLE
Project Miki: Back button from MainActivity 'exits' from application

### ISSUE THREAD

**Issue by arynchoong** [WomenWhoCode/KL-network#8]
The back button from the MainActivity automatically bring the user out of the application, this provides confusion to users. As the MainActivity does not function as a Home Screen.

Solution a) Shift the Welcome Activity as the mainActivity and the Main Activity to become ReceiptPictureActivity.

Solution b) display pop up for user to confirm whether to exit appliction.

**Comment by daphnecys** [comment]
You can override the onBackPressed function to prevent the return to home screen.
http://stackoverflow.com/questions/4779954/disable-back-button-in-android

**Comment by ff55lab** [comment]
simplest solution is to Toast message to user "Press Back again to exit app" after click Back. One more press will quit the app.

**Comment by arynchoong** [comment]
Thanks, ff55lab. That sounds great. :) 
I would go for that: 
Solution f) Toast message to user "Press Back again to exit app" after click Back. One more press will quit the app.
